spring:
  application:
    name: content_manager
  datasource:
    url: jdbc:postgresql://onliver.ru:5432/onliver_content
    username: onliveradmin
    password: onliveradmin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  data:
    redis:
      host: onliver.ru
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

minio:
  endpoint: https://onliver.ru:9443
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name:
    content: content
    avatar: avatar