spring:
  application:
    name: content_manager
  datasource:
    url: jdbc:postgresql://onliver.ru:5432/onliver_content
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  data:
    redis:
      host: onliver.ru
      port: 6379

minio:
  endpoint: http://onliver.ru:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name:
    content: content
    avatar: avatar